max_width=1000000
ideal_width=1000000
fn_call_width=1000000
struct_lit_width=1000000
fn_single_line=true
fn_args_paren_newline=false
reorder_imports=true
hard_tabs=truenormalise_comments=false
match_block_trailing_comma=true
write_mode="Overwrite"
skip_children=false
